#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ContainerGuard AI — 漏洞分析报告生成器。

支持输出格式:
  - Markdown (.md)
  - HTML (.html) — 可直接浏览器打印为 PDF
  - DOCX (.docx) — 使用 python-docx (可选依赖)
"""

import json
import time
from pathlib import Path
from datetime import datetime


# ---- CVE 情报增强数据 (与 intel_agent.BUILTIN_INTEL 同步) ----
CVE_INTEL = {
    "CVE-2021-44228": {"severity": "critical", "desc": "Apache Log4j2 JNDI 注入, 允许远程代码执行 (RCE). CVSS 10.0.", "justification": "漏洞包 log4j-core 2.14.0 存在于 SBOM, JndiLookup 函数在代码路径上"},
    "CVE-2022-22965": {"severity": "critical", "desc": "Spring Framework RCE via ClassPathResource. CVSS 9.8.", "justification": "spring-beans 5.3.15 在受影响版本范围内, ClassPathResource 调用可达"},
    "CVE-2017-5638":  {"severity": "critical", "desc": "Apache Struts2 multipart parser RCE. CVSS 10.0.", "justification": "struts2-core 2.3.31 版本低于修复版 2.5.10.1, multipart 解析器可达"},
    "CVE-2022-42889": {"severity": "critical", "desc": "Apache Commons Text StringSubstitutor RCE. CVSS 9.8.", "justification": "commons-text 1.9 含有插值 RCE 漏洞, StringSubstitutor 存在调用"},
    "CVE-2014-0160":  {"severity": "high", "desc": "OpenSSL Heartbleed 心跳扩展漏洞. CVSS 7.5.", "justification": "OpenSSL 1.0.1f 在受影响版本范围 [1.0.1, 1.0.1g) 内, heartbeat 代码可达"},
    "CVE-2021-3449":  {"severity": "high", "desc": "OpenSSL NULL 指针引用漏洞. CVSS 5.9.", "justification": "OpenSSL 1.1.1j 在受影响范围 [1.1.1, 1.1.1k) 内, signature_algorithms 可达"},
    "CVE-2023-44487": {"severity": "high", "desc": "HTTP/2 Rapid Reset 拒绝服务攻击. CVSS 7.5.", "justification": "golang.org/x/net 0.15.0 低于修复版 0.17.0, RST 帧处理代码可达"},
    "CVE-2021-44906": {"severity": "medium", "desc": "minimist 原型链污染漏洞. CVSS 9.8.", "justification": "minimist 1.2.5 低于修复版 1.2.6, prototype 污染代码可达"},
    "CVE-2023-36632": {"severity": "medium", "desc": "Python email.utils.parseaddr 递归 DoS. CVSS 7.5.", "justification": "容器中未调用 parseaddr 函数 (vulnerable_code_not_in_execute_path)"},
    "CVE-2023-32681": {"severity": "medium", "desc": "Python Requests SSRF. CVSS 6.1.", "justification": "SBOM 中不包含 requests 库 (component_not_present)"},
    "CVE-2024-3094":  {"severity": "critical", "desc": "xz-utils 后门漏洞. CVSS 10.0.", "justification": "xz-utils 版本在受影响范围内"},
    "CVE-2023-24329": {"severity": "medium", "desc": "Python urllib URL 解析绕过. CVSS 7.5.", "justification": "容器中未调用 urllib.parse (vulnerable_code_not_in_execute_path)"},
    "CVE-2022-22947": {"severity": "critical", "desc": "Spring Cloud Gateway RCE. CVSS 10.0.", "justification": "spring-cloud-gateway 版本在受影响范围内"},
}


def _enrich_result(cve_id: str, r: dict) -> dict:
    """从 CVE_INTEL 补充 severity 和 justification。"""
    intel = CVE_INTEL.get(cve_id, {})
    enriched = dict(r)
    if enriched.get("severity", "unknown") == "unknown":
        enriched["severity"] = intel.get("severity", "unknown")
    # 如果 justification 只是一个简单的 status 字符串，替换为真实理由
    raw_just = enriched.get("justification", "")
    if raw_just in ("affected", "not_affected", "unknown", "") or len(raw_just) < 15:
        enriched["justification"] = intel.get("justification", raw_just)
    enriched["description"] = intel.get("desc", "")
    return enriched


def generate_markdown_report(scan_data: dict, target: str = "") -> str:
    """生成 Markdown 格式的漏洞分析报告。"""

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected

    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "unknown": 4}

    md = f"""# 🛡️ ContainerGuard AI — 漏洞分析报告

> **目标**: {target or '未指定'}
> **生成时间**: {now}
> **分析引擎**: 多智能体 AI (llama-3.1-70b-instruct via NVIDIA NIM)

---

## 摘要

| 指标 | 值 |
|:---|:---|
| CVE 总数 | **{total}** |
| Affected | **{affected}** 🔴 |
| Not Affected | **{not_affected}** 🟢 |
| 平均置信度 | **{ours.get('avg_confidence', 0):.0%}** |
| 总耗时 | **{ours.get('total_time', 0):.1f} 秒** |

---

## CVE 详细分析

"""

    sorted_results = sorted(results.items(),
                            key=lambda x: severity_order.get(_enrich_result(x[0], x[1]).get("severity", "unknown"), 4))

    for cve_id, r in sorted_results:
        r = _enrich_result(cve_id, r)
        status_icon = "🔴" if r.get("status") == "affected" else "🟢"
        severity = r.get("severity", "unknown")
        confidence = r.get("confidence", 0)

        md += f"""### {status_icon} {cve_id}

| 属性 | 值 |
|:---|:---|
| **严重程度** | {severity.upper()} |
| **描述** | {r.get('description', 'N/A')} |
| **VEX 判定** | {r.get('status', 'unknown')} |
| **置信度** | {confidence:.0%} |
| **判定理由** | {r.get('justification', 'N/A')} |

---

"""

    md += f"""## 免责声明

本报告由 ContainerGuard AI 多智能体系统自动生成，使用 LLM 推理辅助判定。
结果仅供参考，关键安全决策请结合人工审查。

---

*Generated by ContainerGuard AI v2.0 — {now}*
"""
    return md


def generate_html_report(scan_data: dict, target: str = "") -> str:
    """生成 HTML 格式的漏洞分析报告（可直接打印为 PDF）。"""

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected
    avg_conf = ours.get("avg_confidence", 0)

    rows = ""
    for cve_id, r in sorted(results.items(), key=lambda x: x[0]):
        r = _enrich_result(cve_id, r)
        status = r.get("status", "unknown")
        severity = r.get("severity", "unknown")
        confidence = r.get("confidence", 0)
        sev_class = severity
        status_color = "#ef4444" if status == "affected" else "#22c55e"
        rows += f"""<tr>
            <td style="font-family:monospace;font-weight:600">{cve_id}</td>
            <td><span class="sev {sev_class}">{severity.upper()}</span></td>
            <td style="color:{status_color};font-weight:600">{status}</td>
            <td>{confidence:.0%}</td>
            <td style="font-size:12px;max-width:300px">{r.get('justification', 'N/A')}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>ContainerGuard AI — 漏洞分析报告</title>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono&display=swap');
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: 'Inter', sans-serif; background: #fff; color: #1a1a1a; padding: 40px; max-width: 900px; margin: 0 auto; }}
    h1 {{ font-size: 24px; margin-bottom: 4px; }}
    .subtitle {{ color: #666; font-size: 13px; margin-bottom: 24px; }}
    .stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }}
    .stat {{ text-align: center; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }}
    .stat-val {{ font-size: 28px; font-weight: 700; font-family: 'JetBrains Mono'; }}
    .stat-label {{ font-size: 12px; color: #666; margin-top: 4px; }}
    .stat.danger .stat-val {{ color: #ef4444; }}
    .stat.safe .stat-val {{ color: #22c55e; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 16px; }}
    th {{ text-align: left; padding: 8px 12px; background: #f9fafb; border-bottom: 2px solid #e5e7eb; font-size: 11px; text-transform: uppercase; color: #666; }}
    td {{ padding: 8px 12px; border-bottom: 1px solid #f0f0f0; }}
    tr:hover {{ background: #f9fafb; }}
    .sev {{ padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
    .sev.critical {{ background: #fef2f2; color: #ef4444; }}
    .sev.high {{ background: #fffbeb; color: #f59e0b; }}
    .sev.medium {{ background: #eff6ff; color: #3b82f6; }}
    .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; text-align: center; }}
    @media print {{
        body {{ padding: 20px; }}
        .stat {{ border: 1px solid #ccc; }}
    }}
</style>
</head>
<body>
<h1>🛡️ ContainerGuard AI — 漏洞分析报告</h1>
<p class="subtitle">目标: {target or '未指定'} &nbsp;|&nbsp; 生成时间: {now} &nbsp;|&nbsp; 引擎: llama-3.1-70b-instruct (NVIDIA NIM)</p>

<div class="stats">
    <div class="stat"><div class="stat-val">{total}</div><div class="stat-label">CVE 总数</div></div>
    <div class="stat danger"><div class="stat-val">{affected}</div><div class="stat-label">Affected</div></div>
    <div class="stat safe"><div class="stat-val">{not_affected}</div><div class="stat-label">Not Affected</div></div>
    <div class="stat"><div class="stat-val">{avg_conf:.0%}</div><div class="stat-label">平均置信度</div></div>
</div>

<table>
<thead><tr><th>CVE ID</th><th>严重程度</th><th>VEX 判定</th><th>置信度</th><th>理由</th></tr></thead>
<tbody>{rows}</tbody>
</table>

<div class="footer">
    <p>本报告由 ContainerGuard AI 多智能体系统自动生成 — {now}</p>
    <p>结果仅供参考，关键安全决策请结合人工审查</p>
</div>
</body>
</html>"""
    return html


def generate_docx_report(scan_data: dict, target: str = "", output_path: str = "") -> str:
    """
    生成 DOCX (Word) 格式的漏洞分析报告。

    依赖 python-docx，如果不可用则回退到 HTML。
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
    except ImportError:
        # python-docx 不可用，回退为 HTML
        return None

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected

    doc = Document()

    # 标题
    title = doc.add_heading("ContainerGuard AI — 漏洞分析报告", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"目标: {target or '未指定'}")
    doc.add_paragraph(f"生成时间: {now}")
    doc.add_paragraph(f"分析引擎: llama-3.1-70b-instruct (NVIDIA NIM)")
    doc.add_paragraph("")

    # 摘要表格
    doc.add_heading("摘要", level=1)
    summary_table = doc.add_table(rows=4, cols=2)
    summary_table.style = "Table Grid"
    summary_data = [
        ("CVE 总数", str(total)),
        ("Affected", str(affected)),
        ("Not Affected", str(not_affected)),
        ("平均置信度", f"{ours.get('avg_confidence', 0):.0%}"),
    ]
    for i, (key, val) in enumerate(summary_data):
        summary_table.rows[i].cells[0].text = key
        summary_table.rows[i].cells[1].text = val

    doc.add_paragraph("")
    doc.add_heading("CVE 详细分析", level=1)

    # CVE 表格
    cve_table = doc.add_table(rows=1, cols=5)
    cve_table.style = "Table Grid"
    headers = ["CVE ID", "严重程度", "VEX 判定", "置信度", "理由"]
    for i, h in enumerate(headers):
        cve_table.rows[0].cells[i].text = h
        for run in cve_table.rows[0].cells[i].paragraphs[0].runs:
            run.bold = True

    for cve_id, r in sorted(results.items()):
        r = _enrich_result(cve_id, r)
        row = cve_table.add_row()
        row.cells[0].text = cve_id
        row.cells[1].text = r.get("severity", "unknown").upper()
        row.cells[2].text = r.get("status", "unknown")
        row.cells[3].text = f"{r.get('confidence', 0):.0%}"
        row.cells[4].text = r.get("justification", "N/A")[:80]

    doc.add_paragraph("")
    doc.add_paragraph("本报告由 ContainerGuard AI 多智能体系统自动生成。结果仅供参考。")
    doc.add_paragraph(f"Generated by ContainerGuard AI v2.0 — {now}")

    if not output_path:
        output_path = f"report_{int(time.time())}.docx"

    doc.save(output_path)
    return output_path
