#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ContainerGuard AI — 漏洞分析报告生成器。

支持输出格式:
  - Markdown (.md)
  - HTML (.html) — 可直接浏览器打印为 PDF
  - DOCX (.docx) — 使用 python-docx (可选依赖)
"""

import json
import time
from pathlib import Path
from datetime import datetime


def generate_markdown_report(scan_data: dict, target: str = "") -> str:
    """生成 Markdown 格式的漏洞分析报告。"""

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected

    # 按严重度排序
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "unknown": 4}

    md = f"""# 🛡️ ContainerGuard AI — 漏洞分析报告

> **目标**: {target or '未指定'}
> **生成时间**: {now}
> **分析引擎**: 多智能体 AI (llama-3.1-70b-instruct via NVIDIA NIM)

---

## 摘要

| 指标 | 值 |
|:---|:---|
| CVE 总数 | **{total}** |
| Affected | **{affected}** 🔴 |
| Not Affected | **{not_affected}** 🟢 |
| 平均置信度 | **{ours.get('avg_confidence', 0):.0%}** |
| 总耗时 | **{ours.get('total_time', 0):.1f} 秒** |

---

## CVE 详细分析

"""

    for cve_id, r in sorted(results.items(), key=lambda x: x[0]):
        status_icon = "🔴" if r.get("status") == "affected" else "🟢"
        severity = r.get("severity", "unknown")
        confidence = r.get("confidence", 0)

        md += f"""### {status_icon} {cve_id}

| 属性 | 值 |
|:---|:---|
| **严重程度** | {severity.upper()} |
| **VEX 判定** | {r.get('status', 'unknown')} |
| **置信度** | {confidence:.0%} |
| **理由** | {r.get('justification', 'N/A')} |

---

"""

    md += f"""## 免责声明

本报告由 ContainerGuard AI 多智能体系统自动生成，使用 LLM 推理辅助判定。
结果仅供参考，关键安全决策请结合人工审查。

---

*Generated by ContainerGuard AI v2.0 — {now}*
"""
    return md


def generate_html_report(scan_data: dict, target: str = "") -> str:
    """生成 HTML 格式的漏洞分析报告（可直接打印为 PDF）。"""

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected
    avg_conf = ours.get("avg_confidence", 0)

    rows = ""
    for cve_id, r in sorted(results.items(), key=lambda x: x[0]):
        status = r.get("status", "unknown")
        severity = r.get("severity", "unknown")
        confidence = r.get("confidence", 0)
        sev_class = severity
        status_color = "#ef4444" if status == "affected" else "#22c55e"
        rows += f"""<tr>
            <td style="font-family:monospace;font-weight:600">{cve_id}</td>
            <td><span class="sev {sev_class}">{severity.upper()}</span></td>
            <td style="color:{status_color};font-weight:600">{status}</td>
            <td>{confidence:.0%}</td>
            <td style="font-size:12px;max-width:300px">{r.get('justification', 'N/A')}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>ContainerGuard AI — 漏洞分析报告</title>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono&display=swap');
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: 'Inter', sans-serif; background: #fff; color: #1a1a1a; padding: 40px; max-width: 900px; margin: 0 auto; }}
    h1 {{ font-size: 24px; margin-bottom: 4px; }}
    .subtitle {{ color: #666; font-size: 13px; margin-bottom: 24px; }}
    .stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }}
    .stat {{ text-align: center; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }}
    .stat-val {{ font-size: 28px; font-weight: 700; font-family: 'JetBrains Mono'; }}
    .stat-label {{ font-size: 12px; color: #666; margin-top: 4px; }}
    .stat.danger .stat-val {{ color: #ef4444; }}
    .stat.safe .stat-val {{ color: #22c55e; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 16px; }}
    th {{ text-align: left; padding: 8px 12px; background: #f9fafb; border-bottom: 2px solid #e5e7eb; font-size: 11px; text-transform: uppercase; color: #666; }}
    td {{ padding: 8px 12px; border-bottom: 1px solid #f0f0f0; }}
    tr:hover {{ background: #f9fafb; }}
    .sev {{ padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
    .sev.critical {{ background: #fef2f2; color: #ef4444; }}
    .sev.high {{ background: #fffbeb; color: #f59e0b; }}
    .sev.medium {{ background: #eff6ff; color: #3b82f6; }}
    .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; text-align: center; }}
    @media print {{
        body {{ padding: 20px; }}
        .stat {{ border: 1px solid #ccc; }}
    }}
</style>
</head>
<body>
<h1>🛡️ ContainerGuard AI — 漏洞分析报告</h1>
<p class="subtitle">目标: {target or '未指定'} &nbsp;|&nbsp; 生成时间: {now} &nbsp;|&nbsp; 引擎: llama-3.1-70b-instruct (NVIDIA NIM)</p>

<div class="stats">
    <div class="stat"><div class="stat-val">{total}</div><div class="stat-label">CVE 总数</div></div>
    <div class="stat danger"><div class="stat-val">{affected}</div><div class="stat-label">Affected</div></div>
    <div class="stat safe"><div class="stat-val">{not_affected}</div><div class="stat-label">Not Affected</div></div>
    <div class="stat"><div class="stat-val">{avg_conf:.0%}</div><div class="stat-label">平均置信度</div></div>
</div>

<table>
<thead><tr><th>CVE ID</th><th>严重程度</th><th>VEX 判定</th><th>置信度</th><th>理由</th></tr></thead>
<tbody>{rows}</tbody>
</table>

<div class="footer">
    <p>本报告由 ContainerGuard AI 多智能体系统自动生成 — {now}</p>
    <p>结果仅供参考，关键安全决策请结合人工审查</p>
</div>
</body>
</html>"""
    return html


def generate_docx_report(scan_data: dict, target: str = "", output_path: str = "") -> str:
    """
    生成 DOCX (Word) 格式的漏洞分析报告。

    依赖 python-docx，如果不可用则回退到 HTML。
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
    except ImportError:
        # python-docx 不可用，回退为 HTML
        return None

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ours = scan_data.get("ours", {})
    results = ours.get("results", {})
    total = len(results)
    affected = sum(1 for r in results.values() if r.get("status") == "affected")
    not_affected = total - affected

    doc = Document()

    # 标题
    title = doc.add_heading("ContainerGuard AI — 漏洞分析报告", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"目标: {target or '未指定'}")
    doc.add_paragraph(f"生成时间: {now}")
    doc.add_paragraph(f"分析引擎: llama-3.1-70b-instruct (NVIDIA NIM)")
    doc.add_paragraph("")

    # 摘要表格
    doc.add_heading("摘要", level=1)
    summary_table = doc.add_table(rows=4, cols=2)
    summary_table.style = "Table Grid"
    summary_data = [
        ("CVE 总数", str(total)),
        ("Affected", str(affected)),
        ("Not Affected", str(not_affected)),
        ("平均置信度", f"{ours.get('avg_confidence', 0):.0%}"),
    ]
    for i, (key, val) in enumerate(summary_data):
        summary_table.rows[i].cells[0].text = key
        summary_table.rows[i].cells[1].text = val

    doc.add_paragraph("")
    doc.add_heading("CVE 详细分析", level=1)

    # CVE 表格
    cve_table = doc.add_table(rows=1, cols=5)
    cve_table.style = "Table Grid"
    headers = ["CVE ID", "严重程度", "VEX 判定", "置信度", "理由"]
    for i, h in enumerate(headers):
        cve_table.rows[0].cells[i].text = h
        for run in cve_table.rows[0].cells[i].paragraphs[0].runs:
            run.bold = True

    for cve_id, r in sorted(results.items()):
        row = cve_table.add_row()
        row.cells[0].text = cve_id
        row.cells[1].text = r.get("severity", "unknown").upper()
        row.cells[2].text = r.get("status", "unknown")
        row.cells[3].text = f"{r.get('confidence', 0):.0%}"
        row.cells[4].text = r.get("justification", "N/A")[:80]

    doc.add_paragraph("")
    doc.add_paragraph("本报告由 ContainerGuard AI 多智能体系统自动生成。结果仅供参考。")
    doc.add_paragraph(f"Generated by ContainerGuard AI v2.0 — {now}")

    if not output_path:
        output_path = f"report_{int(time.time())}.docx"

    doc.save(output_path)
    return output_path
